export const questionsFakeData = {
    items: [
        {
            tags: ['python', 'web-scraping'],
            owner: {
                account_id: 27742785,
                reputation: 1,
                user_id: 21178916,
                user_type: 'registered',
                profile_image:
                    'https://lh3.googleusercontent.com/a/AEdFTp6wmT0TCgaVRZ1HvR4t8NpZAgZbWTThD3nPSm3v=k-s256',
                display_name: 'TING',
                link: 'https://stackoverflow.com/users/21178916/ting',
            },
            is_answered: false,
            view_count: 16,
            answer_count: 1,
            score: -2,
            last_activity_date: 1675940351,
            creation_date: 1675935869,
            last_edit_date: 1675937313,
            question_id: 75396773,
            content_license: 'CC BY-SA 4.0',
            link: 'https://stackoverflow.com/questions/75396773/how-to-scrape-lookalike-instagram-accounts-in-python',
            title: 'How to scrape lookalike instagram accounts in python?',
        },
        {
            tags: ['python'],
            owner: {
                account_id: 27743301,
                reputation: 1,
                user_id: 21179286,
                user_type: 'registered',
                profile_image:
                    'https://www.gravatar.com/avatar/b3b0231be66cf0859f5c715b5a695c24?s=256&d=identicon&r=PG',
                display_name: 'saynedbread',
                link: 'https://stackoverflow.com/users/21179286/saynedbread',
            },
            is_answered: false,
            view_count: 17,
            closed_date: 1675940354,
            answer_count: 2,
            score: -3,
            last_activity_date: 1675940345,
            creation_date: 1675940125,
            last_edit_date: 1675940259,
            question_id: 75397592,
            link: 'https://stackoverflow.com/questions/75397592/how-do-i-turn-a-calculation-in-a-variable-to-string',
            closed_reason: 'Duplicate',
            title: 'How do I turn a &quot;calculation&quot; in a variable to string?',
        },
        {
            tags: ['python', 'multithreading', 'qt', 'user-interface', 'xmpp'],
            owner: {
                account_id: 13473500,
                reputation: 1,
                user_id: 9721238,
                user_type: 'registered',
                profile_image:
                    'https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=256',
                display_name: 'christin sugnan',
                link: 'https://stackoverflow.com/users/9721238/christin-sugnan',
            },
            is_answered: false,
            view_count: 2,
            answer_count: 0,
            score: 0,
            last_activity_date: 1675940335,
            creation_date: 1675940335,
            question_id: 75397624,
            content_license: 'CC BY-SA 4.0',
            link: 'https://stackoverflow.com/questions/75397624/qt-designer-qmessagebox-gui-hangs-in-thread',
            title: 'QT Designer Qmessagebox GUI Hangs in Thread',
        },
        {
            tags: ['python'],
            owner: {
                account_id: 24507923,
                reputation: 11,
                user_id: 18422670,
                user_type: 'registered',
                profile_image:
                    'https://graph.facebook.com/1386176588078482/picture?type=large',
                display_name: 'Joseph Badana Rivera',
                link: 'https://stackoverflow.com/users/18422670/joseph-badana-rivera',
            },
            is_answered: true,
            view_count: 57,
            answer_count: 1,
            score: 0,
            last_activity_date: 1675940331,
            creation_date: 1665428141,
            last_edit_date: 1675940331,
            question_id: 74019552,
            content_license: 'CC BY-SA 4.0',
            link: 'https://stackoverflow.com/questions/74019552/drawing-a-window-in-python',
            title: 'Drawing a window in python',
        },
        {
            tags: ['python', 'dataframe', 'merge'],
            owner: {
                account_id: 16698407,
                reputation: 97,
                user_id: 13910525,
                user_type: 'registered',
                profile_image:
                    'https://www.gravatar.com/avatar/8251e838ec199e40d6c6a937b797fde7?s=256&d=identicon&r=PG',
                display_name: 'ImNotSureAboutStats',
                link: 'https://stackoverflow.com/users/13910525/imnotsureaboutstats',
            },
            is_answered: false,
            view_count: 33,
            answer_count: 3,
            score: 0,
            last_activity_date: 1675940279,
            creation_date: 1675932534,
            last_edit_date: 1675940279,
            question_id: 75396170,
            content_license: 'CC BY-SA 4.0',
            link: 'https://stackoverflow.com/questions/75396170/sum-specific-rows-based-on-multiple-conditions',
            title: 'Sum specific rows based on multiple conditions',
        },
    ],
    has_more: true,
    quota_max: 10000,
    quota_remaining: 9986,
};

export const tagsFakeData = {
    items: [
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 2474617,
            name: 'javascript',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 2103844,
            name: 'python',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1887029,
            name: 'java',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1580825,
            name: 'c#',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1455431,
            name: 'php',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1398423,
            name: 'android',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1163845,
            name: 'html',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 1032810,
            name: 'jquery',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 788270,
            name: 'c++',
        },
        {
            has_synonyms: true,
            is_moderator_only: false,
            is_required: false,
            count: 785344,
            name: 'css',
        },
    ],
    has_more: true,
    quota_max: 10000,
    quota_remaining: 9938,
};
